var obj_1 = {
	"title":"有品秒杀",
	"list":[
		{
			"img":"img/ms_1.jpg",
			"name":"瑞幸SOE冻干粉",
			"newPrice":"79",
			"oldPrice":"159",
			"tagImg":["img/tag_1_01.png","img/tag_2_01.png","img/tag_3_01.png","img/tag_4_01.png"],
			"smallImg":["img/small_1_01.png","img/small_2_01.png","img/small_3_01.png","img/small_4_01.png"],
			"bigImg":["img/big_1_01.webp","img/big_2_01.webp","img/big_3_01.webp","img/big_4_01.webp"],
			"cid":"01",
			"xqName":"器屋 木柄青钝色玻璃泡茶杯 茶水分离 青钝初笙杯T型7A",
			"xqDic":"高颜值有色玻璃木把杯"

		},
		{
			"img":"img/ms_2.jpg",
			"name":"谷小酒 谷院烧酒",
			"newPrice":"19.5起",
			"oldPrice":"39",
			"tagImg":["img/tag_1_02.png","img/tag_2_02.png","img/tag_3_02.png","img/tag_4_02.png"],
			"smallImg":["img/small_1_02.png","img/small_2_02.png","img/small_3_02.png","img/small_4_02.png"],
			"bigImg":["img/big_1_02.webp","img/big_2_02.webp","img/big_3_02.webp","img/big_4_02.webp"],
			"cid":"02",
			"xqName":"天外天天然弱碱碱性矿泉水(pH: 7.3-9.9)",
			"xqDic":"超高性价比，国家级双认证，源自云南，口感清冽甘甜"
		},
		{
			"img":"img/ms_3.jpg",
			"name":"单冲锋薄款外套",
			"newPrice":"99",
			"oldPrice":"199",
			"cid":"03",
			"xqName":"",
			"xqDic":""
		},
		{
			"img":"img/ms_4.jpg",
			"name":"懂人话的循环风扇",
			"newPrice":"399起",
			"oldPrice":"799",
			"cid":"04",
			"xqName":"",
			"xqDic":""
		},
		{
			"img":"img/ms_5.jpg",
			"name":"丽得姿面膜",
			"newPrice":"75起",
			"oldPrice":"367",
			"cid":"05",
			"xqName":"",
			"xqDic":""
		},
		{
			"img":"img/ms_6.jpg",
			"name":"东菱全自动咖啡机",
			"newPrice":"399",
			"oldPrice":"799",
			"cid":"06",
			"xqName":"",
			"xqDic":""
		},
		{
			"img":"img/ms_7.jpg",
			"name":"纯棉印花件套",
			"newPrice":"149起",
			"oldPrice":"299",
			"cid":"07",
			"xqName":"",
			"xqDic":""
		}
	]
}
var obj_2 = {
	"title":"每日新品",
	"list":[
		{
			"title":"新品第一组",
			"list":[
				{
					"img":"img/xp_1.jpg",
					"name":"MIX 4",
					"dic":"CPU全面屏|真彩原色+120Hz；一...",
					"price":"4999起",
					"cid":"001"
				},
				{
					"img":"img/xp_2.jpg",
					"name":"鱼跃8F-5AW",
					"dic":"医用经典款，5L流量氧浓度达9...",
					"price":"3580",
					"cid":"002"
				},
				{
					"img":"img/xp_3.jpg",
					"name":"撒隆巴斯140片",
					"dic":"轻松解决疼痛烦恼",
					"price":"92起",
					"cid":"003"
				},
				{
					"img":"img/xp_4.jpg",
					"name":"磁吸快充鼠标垫",
					"dic":"磁吸无线快充 磁吸鼠标垫 Qi无...",
					"price":"169",
					"cid":"004"
				}
			]
		},
		{
			"title":"新品第二组",
			"list":[
				{
					"img":"img/xp_5.jpg",
					"name":"十双装抗菌健康袜",
					"dic":"两件9折，银离子抗菌，无感袜头...",
					"price":"49起",
					"cid":"001"
				},
				{
					"img":"img/xp_6.jpg",
					"name":"知吾煮方形锅",
					"dic":"方形不粘汤锅+方形不粘烤盘套装...",
					"price":"349",
					"cid":"002"
				},
				{
					"img":"img/xp_7.jpg",
					"name":"扫托机器人2Pro",
					"dic":"每分钟10000次高频震动拖，Al智...",
					"price":"2699",
					"cid":"003"
				},
				{
					"img":"img/xp_8.jpg",
					"name":"稀雀四叶草快客杯",
					"dic":"随身携带的小幸运，北宋经典名...",
					"price":"168",
					"cid":"004"
				}
			]
		},
		{
			"title":"新品第三组",
			"list":[
				{
					"img":"img/xp_9.jpg",
					"name":"米家侧吸烟灶套装",
					"dic":"挥手即排，烟灶联动，20㎡/min...",
					"price":"699起",
					"cid":"001"
				},
				{
					"img":"img/xp_10.jpg",
					"name":"咖啡因眼部精华",
					"dic":"性价比超高的眼部精华，去水肿...",
					"price":"79",
					"cid":"002"
				},
				{
					"img":"img/xp_11.jpg",
					"name":"三室一厅空调套装",
					"dic":"UVC紫外除菌率99.9%·新1级·一键...",
					"price":"6798起",
					"cid":"003"
				},
				{
					"img":"img/xp_12.jpg",
					"name":"小仓熊除烟味香水",
					"dic":"植物萃取，清新木质香，香味持...",
					"price":"59起",
					"cid":"004"
				}
			]
		}
	]
}
var obj_3 = {
	"title":"专属推荐",
	"list":[
		{
			"img":"img/tj_1.jpg",
			"dic":"新疆阿克苏棉，强大吸水性",
			"tag":"特价",
			"name":"纯棉抗菌毛巾",
			"price":"39起"
		},
		{
			"img":"img/tj_2.png",
			"dic":"超高性价比，超值享受体验",
			"tag":"有品定制",
			"name":"摩摩哒智能按摩椅",
			"price":"5999起"
		},
		{
			"img":"img/tj_3.png",
			"dic":"抗菌涂层抗菌率>99.99%",
			"tag":"小米自营",
			"name":"空气净化器滤芯",
			"price":"169"
		},
		{
			"img":"img/tj_4.png",
			"dic":"宿舍必备幸福好物，性价比高携...",
			"tag":"HOT",
			"name":"8H 零压记忆棉床垫枕头...",
			"price":"319"
		},
		{
			"img":"img/tj_5.jpg",
			"dic":"杀菌抗菌强力去污",
			"tag":"满折",
			"name":"洗衣机槽清洗剂",
			"price":"39起"
		},
		{
			"img":"img/tj_6.png",
			"dic":"多场景使用，可拆卸折叠",
			"tag":"特价",
			"name":"多功能折叠小桌板",
			"price":"87"
		},
		{
			"img":"img/tj_7.jpg",
			"dic":"保护口腔健康",
			"tag":"特价",
			"name":"辅酶Q10绿茶牙膏",
			"price":"9.9起"
		},
		{
			"img":"img/tj_8.jpg",
			"dic":"五年陈放，糯香茶化石",
			"tag":"特价",
			"name":"五年陈糯香碎银子",
			"price":"35起"
		},
		{
			"img":"img/tj_9.jpg",
			"dic":"99.9%抑菌率|植物精华",
			"tag":"7天价保",
			"name":"泡沫抑菌洗手液",
			"price":"39.9"
		},
		{
			"img":"img/tj_10.jpg",
			"dic":"奥莱直采 美国直邮",
			"tag":"有品海购",
			"name":"蔻驰老花手拎包",
			"price":"469"
		},
		{
			"img":"img/tj_11.png",
			"dic":"白领体验套餐-基础版",
			"tag":"满折",
			"name":"白领体验套餐",
			"price":"658"
		},
		{
			"img":"img/tj_12.jpg",
			"dic":"uv400阻隔紫外线，防眩光",
			"tag":"小米自营",
			"name":"飞行员太阳镜",
			"price":"89"
		}
	]
}
